-- MySQL Script generated by MySQL Workbench
-- Mon Sep  2 20:05:49 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dw2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dw2` ;

-- -----------------------------------------------------
-- Schema dw2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dw2` DEFAULT CHARACTER SET utf8 ;
USE `dw2` ;

-- -----------------------------------------------------
-- Table `dw2`.`times`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw2`.`times` ;

CREATE TABLE IF NOT EXISTS `dw2`.`times` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `estadio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw2`.`posicoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw2`.`posicoes` ;

CREATE TABLE IF NOT EXISTS `dw2`.`posicoes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw2`.`jogadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw2`.`jogadores` ;

CREATE TABLE IF NOT EXISTS `dw2`.`jogadores` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `data_nascimento` VARCHAR(45) NOT NULL,
  `apelido` VARCHAR(45) NULL,
  `camisa` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `time_id` INT UNSIGNED NOT NULL,
  `posicao_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `fk_jogadores_times1_idx` (`time_id` ASC) ,
  INDEX `fk_jogadores_posicoes1_idx` (`posicao_id` ASC) ,
  CONSTRAINT `fk_jogadores_times1`
    FOREIGN KEY (`time_id`)
    REFERENCES `dw2`.`times` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jogadores_posicoes1`
    FOREIGN KEY (`posicao_id`)
    REFERENCES `dw2`.`posicoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw2`.`tecnicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw2`.`tecnicos` ;

CREATE TABLE IF NOT EXISTS `dw2`.`tecnicos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `data_nascimento` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `times_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `fk_tecnicos_times1_idx` (`times_id` ASC) ,
  CONSTRAINT `fk_tecnicos_times1`
    FOREIGN KEY (`times_id`)
    REFERENCES `dw2`.`times` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw2`.`arbitros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw2`.`arbitros` ;

CREATE TABLE IF NOT EXISTS `dw2`.`arbitros` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `data_nascimento` VARCHAR(45) NOT NULL,
  `nacionalidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw2`.`estados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw2`.`estados` ;

CREATE TABLE IF NOT EXISTS `dw2`.`estados` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sigla` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw2`.`cidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw2`.`cidades` ;

CREATE TABLE IF NOT EXISTS `dw2`.`cidades` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `estado_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `fk_cidades_estados1_idx` (`estado_id` ASC) ,
  CONSTRAINT `fk_cidades_estados1`
    FOREIGN KEY (`estado_id`)
    REFERENCES `dw2`.`estados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw2`.`estadios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw2`.`estadios` ;

CREATE TABLE IF NOT EXISTS `dw2`.`estadios` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cidade_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `fk_estadios_cidades1_idx` (`cidade_id` ASC) ,
  CONSTRAINT `fk_estadios_cidades1`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `dw2`.`cidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw2`.`rodadas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw2`.`rodadas` ;

CREATE TABLE IF NOT EXISTS `dw2`.`rodadas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `data` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw2`.`partidas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw2`.`partidas` ;

CREATE TABLE IF NOT EXISTS `dw2`.`partidas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `arbitro_id` INT UNSIGNED NOT NULL,
  `visitante_id` INT UNSIGNED NOT NULL,
  `mandante_id` INT UNSIGNED NOT NULL,
  `estadio_id` INT UNSIGNED NOT NULL,
  `rodada_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `fk_partidas_arbitros1_idx` (`arbitro_id` ASC) ,
  INDEX `fk_partidas_times2_idx` (`visitante_id` ASC) ,
  INDEX `fk_partidas_times1_idx` (`mandante_id` ASC) ,
  INDEX `fk_partidas_estadios1_idx` (`estadio_id` ASC) ,
  INDEX `fk_partidas_rodadas1_idx` (`rodada_id` ASC) ,
  CONSTRAINT `fk_partidas_arbitros1`
    FOREIGN KEY (`arbitro_id`)
    REFERENCES `dw2`.`arbitros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_partidas_times2`
    FOREIGN KEY (`visitante_id`)
    REFERENCES `dw2`.`times` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_partidas_times1`
    FOREIGN KEY (`mandante_id`)
    REFERENCES `dw2`.`times` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_partidas_estadios1`
    FOREIGN KEY (`estadio_id`)
    REFERENCES `dw2`.`estadios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_partidas_rodadas1`
    FOREIGN KEY (`rodada_id`)
    REFERENCES `dw2`.`rodadas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw2`.`classificados_libertadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw2`.`classificados_libertadores` ;

CREATE TABLE IF NOT EXISTS `dw2`.`classificados_libertadores` (
  `time_id` INT UNSIGNED NOT NULL,
  INDEX `fk_classificados_libertadores_times1_idx` (`time_id` ASC) ,
  CONSTRAINT `fk_classificados_libertadores_times1`
    FOREIGN KEY (`time_id`)
    REFERENCES `dw2`.`times` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw2`.`rebaixados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw2`.`rebaixados` ;

CREATE TABLE IF NOT EXISTS `dw2`.`rebaixados` (
  `time_id` INT UNSIGNED NOT NULL,
  INDEX `fk_rebaixados_times1_idx` (`time_id` ASC) ,
  CONSTRAINT `fk_rebaixados_times1`
    FOREIGN KEY (`time_id`)
    REFERENCES `dw2`.`times` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw2`.`classificados_sul_americana`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw2`.`classificados_sul_americana` ;

CREATE TABLE IF NOT EXISTS `dw2`.`classificados_sul_americana` (
  `time_id` INT UNSIGNED NOT NULL,
  INDEX `fk_classificados_sul_americana_times1_idx` (`time_id` ASC) ,
  CONSTRAINT `fk_classificados_sul_americana_times1`
    FOREIGN KEY (`time_id`)
    REFERENCES `dw2`.`times` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw2`.`artilheiros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw2`.`artilheiros` ;

CREATE TABLE IF NOT EXISTS `dw2`.`artilheiros` (
  `jogador_id` INT UNSIGNED NOT NULL,
  INDEX `fk_artilheiros_jogadores1_idx` (`jogador_id` ASC) ,
  CONSTRAINT `fk_artilheiros_jogadores1`
    FOREIGN KEY (`jogador_id`)
    REFERENCES `dw2`.`jogadores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw2`.`goleiros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw2`.`goleiros` ;

CREATE TABLE IF NOT EXISTS `dw2`.`goleiros` (
  `jogador_id` INT UNSIGNED NOT NULL,
  INDEX `fk_goleiros_jogadores1_idx` (`jogador_id` ASC) ,
  CONSTRAINT `fk_goleiros_jogadores1`
    FOREIGN KEY (`jogador_id`)
    REFERENCES `dw2`.`jogadores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw2`.`classificacao_geral`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw2`.`classificacao_geral` ;

CREATE TABLE IF NOT EXISTS `dw2`.`classificacao_geral` (
  `time_id` INT UNSIGNED NOT NULL,
  INDEX `fk_classificacao_geral_times1_idx` (`time_id` ASC) ,
  CONSTRAINT `fk_classificacao_geral_times1`
    FOREIGN KEY (`time_id`)
    REFERENCES `dw2`.`times` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw2`.`escalacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw2`.`escalacoes` ;

CREATE TABLE IF NOT EXISTS `dw2`.`escalacoes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `partida_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_escalacoes_partidas1_idx` (`partida_id` ASC) ,
  CONSTRAINT `fk_escalacoes_partidas1`
    FOREIGN KEY (`partida_id`)
    REFERENCES `dw2`.`partidas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw2`.`escalacoes_has_jogadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw2`.`escalacoes_has_jogadores` ;

CREATE TABLE IF NOT EXISTS `dw2`.`escalacoes_has_jogadores` (
  `escalacoes_id` INT UNSIGNED NOT NULL,
  `jogadores_id` INT UNSIGNED NOT NULL,
  `posicao_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`escalacoes_id`, `jogadores_id`),
  INDEX `fk_escalacoes_has_jogadores_jogadores1_idx` (`jogadores_id` ASC) ,
  INDEX `fk_escalacoes_has_jogadores_escalacoes_idx` (`escalacoes_id` ASC) ,
  INDEX `fk_escalacoes_has_jogadores_posicoes1_idx` (`posicao_id` ASC) ,
  CONSTRAINT `fk_escalacoes_has_jogadores_escalacoes`
    FOREIGN KEY (`escalacoes_id`)
    REFERENCES `dw2`.`escalacoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_escalacoes_has_jogadores_jogadores1`
    FOREIGN KEY (`jogadores_id`)
    REFERENCES `dw2`.`jogadores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_escalacoes_has_jogadores_posicoes1`
    FOREIGN KEY (`posicao_id`)
    REFERENCES `dw2`.`posicoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw2`.`substituicoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw2`.`substituicoes` ;

CREATE TABLE IF NOT EXISTS `dw2`.`substituicoes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tempo` VARCHAR(45) NOT NULL,
  `escalacao_id` INT UNSIGNED NOT NULL,
  `jogadores_in_id` INT UNSIGNED NOT NULL,
  `jogadores_out_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_substituicoes_escalacoes1_idx` (`escalacao_id` ASC) ,
  INDEX `fk_substituicoes_jogadores1_idx` (`jogadores_in_id` ASC) ,
  INDEX `fk_substituicoes_jogadores2_idx` (`jogadores_out_id` ASC) ,
  CONSTRAINT `fk_substituicoes_escalacoes1`
    FOREIGN KEY (`escalacao_id`)
    REFERENCES `dw2`.`escalacoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_substituicoes_jogadores1`
    FOREIGN KEY (`jogadores_in_id`)
    REFERENCES `dw2`.`jogadores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_substituicoes_jogadores2`
    FOREIGN KEY (`jogadores_out_id`)
    REFERENCES `dw2`.`jogadores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
