-- MySQL Script generated by MySQL Workbench
-- Mon Aug 26 21:45:13 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`times`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`times` ;

CREATE TABLE IF NOT EXISTS `mydb`.`times` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `estadio` VARCHAR(45) NOT NULL,
  `tecnico_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`posicoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`posicoes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`posicoes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`jogadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`jogadores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`jogadores` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `data_nascimento` VARCHAR(45) NOT NULL,
  `apelido` VARCHAR(45) NULL,
  `camisa` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `time_id` INT UNSIGNED NOT NULL,
  `posicao_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_jogadores_times1_idx` (`time_id` ASC) VISIBLE,
  INDEX `fk_jogadores_posicoes1_idx` (`posicao_id` ASC) VISIBLE,
  CONSTRAINT `fk_jogadores_times1`
    FOREIGN KEY (`time_id`)
    REFERENCES `mydb`.`times` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jogadores_posicoes1`
    FOREIGN KEY (`posicao_id`)
    REFERENCES `mydb`.`posicoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tecnicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tecnicos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tecnicos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `data_nascimento` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `times_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_tecnicos_times1_idx` (`times_id` ASC) VISIBLE,
  CONSTRAINT `fk_tecnicos_times1`
    FOREIGN KEY (`times_id`)
    REFERENCES `mydb`.`times` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`arbitros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`arbitros` ;

CREATE TABLE IF NOT EXISTS `mydb`.`arbitros` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `data_nascimento` VARCHAR(45) NOT NULL,
  `nacionalidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estados` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estados` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sigla` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cidades` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cidades` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `estado_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_cidades_estados1_idx` (`estado_id` ASC) VISIBLE,
  CONSTRAINT `fk_cidades_estados1`
    FOREIGN KEY (`estado_id`)
    REFERENCES `mydb`.`estados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estadios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estadios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estadios` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cidade_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_estadios_cidades1_idx` (`cidade_id` ASC) VISIBLE,
  CONSTRAINT `fk_estadios_cidades1`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `mydb`.`cidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rodadas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rodadas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`rodadas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `data` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`partidas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`partidas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`partidas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `arbitro_id` INT UNSIGNED NOT NULL,
  `visitante_id` INT UNSIGNED NOT NULL,
  `mandante_id` INT UNSIGNED NOT NULL,
  `estadio_id` INT UNSIGNED NOT NULL,
  `rodada_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_partidas_arbitros1_idx` (`arbitro_id` ASC) VISIBLE,
  INDEX `fk_partidas_times2_idx` (`visitante_id` ASC) VISIBLE,
  INDEX `fk_partidas_times1_idx` (`mandante_id` ASC) VISIBLE,
  INDEX `fk_partidas_estadios1_idx` (`estadio_id` ASC) VISIBLE,
  INDEX `fk_partidas_rodadas1_idx` (`rodada_id` ASC) VISIBLE,
  CONSTRAINT `fk_partidas_arbitros1`
    FOREIGN KEY (`arbitro_id`)
    REFERENCES `mydb`.`arbitros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_partidas_times2`
    FOREIGN KEY (`visitante_id`)
    REFERENCES `mydb`.`times` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_partidas_times1`
    FOREIGN KEY (`mandante_id`)
    REFERENCES `mydb`.`times` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_partidas_estadios1`
    FOREIGN KEY (`estadio_id`)
    REFERENCES `mydb`.`estadios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_partidas_rodadas1`
    FOREIGN KEY (`rodada_id`)
    REFERENCES `mydb`.`rodadas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`classificados_libertadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`classificados_libertadores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`classificados_libertadores` (
  `time_id` INT UNSIGNED NOT NULL,
  INDEX `fk_classificados_libertadores_times1_idx` (`time_id` ASC) VISIBLE,
  CONSTRAINT `fk_classificados_libertadores_times1`
    FOREIGN KEY (`time_id`)
    REFERENCES `mydb`.`times` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rebaixados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rebaixados` ;

CREATE TABLE IF NOT EXISTS `mydb`.`rebaixados` (
  `time_id` INT UNSIGNED NOT NULL,
  INDEX `fk_rebaixados_times1_idx` (`time_id` ASC) VISIBLE,
  CONSTRAINT `fk_rebaixados_times1`
    FOREIGN KEY (`time_id`)
    REFERENCES `mydb`.`times` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`classificados_sul_americana`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`classificados_sul_americana` ;

CREATE TABLE IF NOT EXISTS `mydb`.`classificados_sul_americana` (
  `time_id` INT UNSIGNED NOT NULL,
  INDEX `fk_classificados_sul_americana_times1_idx` (`time_id` ASC) VISIBLE,
  CONSTRAINT `fk_classificados_sul_americana_times1`
    FOREIGN KEY (`time_id`)
    REFERENCES `mydb`.`times` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`artilheiros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`artilheiros` ;

CREATE TABLE IF NOT EXISTS `mydb`.`artilheiros` (
  `jogador_id` INT UNSIGNED NOT NULL,
  INDEX `fk_artilheiros_jogadores1_idx` (`jogador_id` ASC) VISIBLE,
  CONSTRAINT `fk_artilheiros_jogadores1`
    FOREIGN KEY (`jogador_id`)
    REFERENCES `mydb`.`jogadores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`goleiros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`goleiros` ;

CREATE TABLE IF NOT EXISTS `mydb`.`goleiros` (
  `jogador_id` INT UNSIGNED NOT NULL,
  INDEX `fk_goleiros_jogadores1_idx` (`jogador_id` ASC) VISIBLE,
  CONSTRAINT `fk_goleiros_jogadores1`
    FOREIGN KEY (`jogador_id`)
    REFERENCES `mydb`.`jogadores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`classificacao_geral`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`classificacao_geral` ;

CREATE TABLE IF NOT EXISTS `mydb`.`classificacao_geral` (
  `time_id` INT UNSIGNED NOT NULL,
  INDEX `fk_classificacao_geral_times1_idx` (`time_id` ASC) VISIBLE,
  CONSTRAINT `fk_classificacao_geral_times1`
    FOREIGN KEY (`time_id`)
    REFERENCES `mydb`.`times` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`escalacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`escalacoes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`escalacoes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `partida_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_escalacoes_partidas1_idx` (`partida_id` ASC) VISIBLE,
  CONSTRAINT `fk_escalacoes_partidas1`
    FOREIGN KEY (`partida_id`)
    REFERENCES `mydb`.`partidas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`escalacoes_has_jogadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`escalacoes_has_jogadores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`escalacoes_has_jogadores` (
  `escalacoes_id` INT UNSIGNED NOT NULL,
  `jogadores_id` INT UNSIGNED NOT NULL,
  `posicao_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`escalacoes_id`, `jogadores_id`),
  INDEX `fk_escalacoes_has_jogadores_jogadores1_idx` (`jogadores_id` ASC) VISIBLE,
  INDEX `fk_escalacoes_has_jogadores_escalacoes_idx` (`escalacoes_id` ASC) VISIBLE,
  INDEX `fk_escalacoes_has_jogadores_posicoes1_idx` (`posicao_id` ASC) VISIBLE,
  CONSTRAINT `fk_escalacoes_has_jogadores_escalacoes`
    FOREIGN KEY (`escalacoes_id`)
    REFERENCES `mydb`.`escalacoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_escalacoes_has_jogadores_jogadores1`
    FOREIGN KEY (`jogadores_id`)
    REFERENCES `mydb`.`jogadores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_escalacoes_has_jogadores_posicoes1`
    FOREIGN KEY (`posicao_id`)
    REFERENCES `mydb`.`posicoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
