-- MySQL Script generated by MySQL Workbench
-- Mon Sep  2 20:05:49 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dw2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dw2` ;

-- -----------------------------------------------------
-- Schema dw2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dw2` DEFAULT CHARACTER SET utf8 ;
USE `dw2` ;

-- -----------------------------------------------------
-- Table `dw2`.`bandeja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw2`.`bandeja` ;

CREATE TABLE IF NOT EXISTS `dw2`.`bandeja` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TEXT NOT NULL,
  `preco` FLOAT(5,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)
)ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dw2`.`massa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw2`.`massa` ;

CREATE TABLE IF NOT EXISTS `dw2`.`massa` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TEXT NOT NULL,
  `preco` FLOAT(5,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)
)ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dw2`.`sabor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw2`.`sabor` ;

CREATE TABLE IF NOT EXISTS `dw2`.`sabor` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TEXT NOT NULL,
  `preco` FLOAT(5,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)
)ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dw2`.`cobertura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw2`.`cobertura` ;

CREATE TABLE IF NOT EXISTS `dw2`.`cobertura` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TEXT NOT NULL,
  `preco` FLOAT(5,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)
)ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dw2`.`confeito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw2`.`confeito` ;

CREATE TABLE IF NOT EXISTS `dw2`.`confeito` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TEXT NOT NULL,
  `preco` FLOAT(5,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)
)ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dw2`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw2`.`status` ;

CREATE TABLE IF NOT EXISTS `dw2`.`status` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)
)ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dw2`.`pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw2`.`pessoa` ;

CREATE TABLE IF NOT EXISTS `dw2`.`pessoa` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `bairro` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)
)ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dw2`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw2`.`pedido` ;

CREATE TABLE IF NOT EXISTS `dw2`.`pedido` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `preco` VARCHAR(45) NOT NULL,
  `data_pedido` VARCHAR(45) NOT NULL,
  `data_entrega` VARCHAR(45) NOT NULL,
  `status_id` INT UNSIGNED NOT NULL,
  `bandeja_id` INT UNSIGNED NOT NULL,
  `massa_id` INT UNSIGNED NOT NULL,
  `sabor1_id` INT UNSIGNED NOT NULL,
  `sabor2_id` INT UNSIGNED NOT NULL,
  `cobertura_id` INT UNSIGNED NOT NULL,
  `confeito_id` INT UNSIGNED NOT NULL,
  `pessoa_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `fk_pedido_status_idx` (`status_id` ASC) ,
  INDEX `fk_pedido_bandeja_idx` (`bandeja_id` ASC) ,
  INDEX `fk_pedido_massa_idx` (`massa_id` ASC) ,
  INDEX `fk_pedido_sabor1_idx` (`sabor1_id` ASC) ,
  INDEX `fk_pedido_sabor2_idx` (`sabor2_id` ASC) ,
  INDEX `fk_pedido_cobertura_idx` (`cobertura_id` ASC) ,
  INDEX `fk_pedido_confeito_idx` (`confeito_id` ASC) ,
  INDEX `fk_pedido_pessoa_idx` (`pessoa_id` ASC) ,
  CONSTRAINT `fk_pedido_status`
    FOREIGN KEY (`status_id`)
    REFERENCES `dw2`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_bandeja`
    FOREIGN KEY (`bandeja_id`)
    REFERENCES `dw2`.`bandeja` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_massa`
    FOREIGN KEY (`massa_id`)
    REFERENCES `dw2`.`massa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_sabor1`
    FOREIGN KEY (`sabor1_id`)
    REFERENCES `dw2`.`sabor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_sabor2`
    FOREIGN KEY (`sabor2_id`)
    REFERENCES `dw2`.`sabor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_cobertura`
    FOREIGN KEY (`cobertura_id`)
    REFERENCES `dw2`.`cobertura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_confeito`
    FOREIGN KEY (`confeito_id`)
    REFERENCES `dw2`.`confeito` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_pessoa`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `dw2`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dw2`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dw2`.`admin` ;

CREATE TABLE IF NOT EXISTS `dw2`.`admin` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)
)ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
